

spring:
  thymeleaf:
    encoding: UTF-8  #???? ??
    cache: false #??????????
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5 #?????HTML5 ???HTML5
    servlet:
      content-type: text/html
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd
  redis:
    port: 6379
    password: 123456
    host: 192.168.110.134
    lettuce:
      pool:
        max-active: 8 # ????????????????????
        max-idle: 8 # ???????????
        min-idle: 0 # ???????????
        max-wait: 1000 # ???????????????????????
      shutdown-timeout: 100   # ??????
server:
  port: 8081
